import ReactMarkdown from "react-markdown"
import { PlanActions } from "./PlanActions"

export function PlanView({ title, svgData, roadmapText, summary, projectId, shareToken }: {
  title: string
  svgData: string
  roadmapText: string
  summary?: string
  projectId?: string
  shareToken?: string | null
}) {
  return (
    <div style={{ maxWidth: 760, margin: "0 auto", padding: "40px 32px" }}>
      <div className="display" style={{ fontSize: 22 }}>{title}</div>
      <div className="chalk-line" style={{ marginTop: 10, marginBottom: 14 }} />
      {summary && (
        <p className="mono" style={{ fontSize: 12, color: "var(--steel)", margin: "0 0 20px" }}>{summary}</p>
      )}

      <div className="no-print">
        <PlanActions projectId={projectId} initialToken={shareToken} />
      </div>

      <div className="display" style={{ fontSize: 17 }}>Floor Plan</div>
      <div className="chalk-line" style={{ marginTop: 8, marginBottom: 20 }} />
      <div style={{ border: "1px solid var(--border)", background: "white", padding: 16, marginBottom: 40 }}
        dangerouslySetInnerHTML={{ __html: svgData }} />

      <div className="display" style={{ fontSize: 17 }}>Roadmap</div>
      <div className="chalk-line" style={{ marginTop: 8, marginBottom: 20 }} />
      <div className="msg-content" style={{ borderLeft: "3px solid var(--steel)", paddingLeft: 16 }}>
        <ReactMarkdown>{roadmapText}</ReactMarkdown>
      </div>

      <p className="mono" style={{ fontSize: 11, color: "var(--steel)", marginTop: 40, lineHeight: 1.6 }}>
        Generated by Construction AI as planning guidance only. Layouts and figures must be verified against
        your local municipal byelaws and reviewed by a licensed architect or structural engineer before construction.
      </p>
    </div>
  )
}